.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. hellebit_qt test_hellebit_qt
clean: FORCE
	$(MAKE) -C .. hellebit_qt_clean test_hellebit_qt_clean
check: FORCE
	$(MAKE) -C .. test_hellebit_qt_check
hellebit-qt hellebit-qt.exe: FORCE
	 $(MAKE) -C .. hellebit_qt
